### ISSUE TITLE
Finish all TODO fields

### ISSUE THREAD

**Issue by Aveline-art** [Aveline-art/studious-lamp#5]
### Dependency

When all other MVP issues are finished

### Action Items

- [x] TODO usually represents areas where the code could be better, so they do not need to be resolved now
- [x] resolve all todo areas
  - [x] do a one-over to make sure the code makes sense
  - [x] refactor as needed

**Comment by Aveline-art** [comment]
Completed!
